### PR TITLE
feat: Add `column_decltype` feature from rusqlite

### PR DESCRIPTION
**Pull request by vrongmeal**

### CODE REVIEW

**Review by ryanfowler — APPROVED** [review]
Thanks, LGTM!

**Comment by vrongmeal** [comment]
@ryanfowler can we cut a release for this (`0.2.2`)?

**Comment by ryanfowler** [comment]
Released! https://crates.io/crates/async-sqlite/0.2.2

**Comment by vrongmeal** [comment]
This is awesome! Thanks 😀

**Pull request merged**
